apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-6i7h
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-6i7h
    app.kubernetes.io/part-of: ci10t-786-0004-app
  name: devfile-sample-6i7h
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-6i7h
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-6i7h
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0004-tenant/ci10t-786-0004-app/devfile-sample-6i7h@sha256:bee3440c9571765da8a1cacb02f9d9d68ea0e52add21d590470e99fe481ceb57
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
