apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-6i7h
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0004-tenant/ci10t-786-0004-app/devfile-sample-6i7h@sha256:bee3440c9571765da8a1cacb02f9d9d68ea0e52add21d590470e99fe481ceb57
        name: my-nodejs
        resources: {}
status: {}
